config:
  hidePrivate: True
  codeComposationOtherColor: '#000000'
  # dateFormat: StartEnd # use custom format


projects:
  benshen98.github.io:
    title: Portfolio
    category: Extracurricular
    previewSrc: projects/portfolio/preview.js # add to validation
    imgSrc: projects/portfolio/front.png # add to validation
    footerIcons: [Gcloud, React, Material]


  raft:
    title: Raft Consensus
    category: Academic
    previewSrc: projects/raft/preview.js # add to validation
    imgSrc: projects/raft/front.png # add to validation
    footerIcons: [Elixir]
    reportSrc: projects/raft/raftReport.pdf
    webpageHref:

  robotics:
    title: Probabilistic Localization
    category: Academic
    previewSrc: projects/robotics/preview.js
    imgSrc: projects/robotics/front.gif
    footerIcons: [BrickPi, Python, Lego]

  smart_home:
    title: Smart Home
    category: Extracurricular
    previewSrc: projects/smart_home/preview.js
    imgSrc: projects/smart_home/front.jpg
    footerIcons: [Docker, Balena, Zigbee2MQTT]

  RTOS-MotorControl-HashCompute:
    title: Real Time Concurrent Controller
    category: Academic
    previewSrc: projects/RTOS/preview.js
    imgSrc: projects/RTOS/front.jpg
    reportSrc: projects/RTOS/RTOSReport.pdf
    footerIcons: [CPP]


  C90Compiler:
    title: C90 Compiler
    category: Academic
    previewSrc: projects/compiler/preview.js
    imgSrc: projects/compiler/front.png
    footerIcons: [CPP, Bison]


  mips:
    title: CPU Simulator
    category: Academic
    previewSrc: projects/mips/preview.js
    imgSrc: projects/mips/front.png
    footerIcons: [CPP]
