config:
  hidePrivate: True
  codeComposationOtherColor: '#000000'
  # dateFormat: StartEnd # use custom format


projects:
  benshen98.github.io:
    title: Portfolio
    category: Extracurricular
    previewSrc: projects/portfolio/preview.js # add to validation
    imgSrc: projects/portfolio/front.png # add to validation
    footerIcons: [Gcloud, React, Material]


  raft:
    title: Raft Consensus
    category: Academic
    previewSrc: projects/raft/preview.js # add to validation
    imgSrc: projects/raft/front.png # add to validation
    footerIcons: [Elixir]
    reportSrc: projects/raft/raftReport.pdf
    webpageHref:

  robotics:
    title: Probabilistic Localization
    category: Academic
    previewSrc: projects/robotics/preview.js
    imgSrc: projects/robotics/front.gif
    footerIcons: [BrickPi, Python, Lego]
